version: "3.7"
services:

  db:
    image: postgres:12.2
    container_name: db_sensors
    ports:
      - "5432:5432"
    #volumes:
      #- /c/Users/invidia/Desktop/Dyster-monitor/server_code/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      #- ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      #- pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: xbee
