# Generated by Django 3.1.2 on 2020-11-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.IntegerField(max_length=50)),
                ('temperature', models.IntegerField(max_length=50)),
                ('humidity', models.IntegerField(max_length=50)),
                ('timestamp', models.IntegerField(max_length=50)),
            ],
        ),
    ]
