# Generated by Django 3.1.2 on 2020-11-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ardxbwsn_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='humidity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensor_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='temperature',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='timestamp',
            field=models.IntegerField(),
        ),
    ]
